# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

# Suppress the warning with the online Travis WebLint
language: generic

sudo: required
dist: trusty

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0

# For windows build (win32) use linux wine.
matrix:
  include:
    - os: linux
      env: LAZ_VER=$PROJECT_LAZARUS_VERSION  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=$PROJECT_LAZARUS_VERSION
    - os: osx
      env: LAZ_VER=$PROJECT_LAZARUS_VERSION
      osx_image: $PROJECT_OSX_IMAGE


before_install:
# Start virtual display server
  - Xvfb $DISPLAY &

install:
# Install prerequisites (fpc/lazarus/wine/qemu)
  - ./travis-lazarus/.travis.install.py

script:
# Build trackereditor project (Debug mode)
  - lazbuild --build-mode=Debug $LAZ_OPT $PROJECT_LPI_EDITOR_PATH

# Build unit test project (Debug mode)
  - lazbuild --build-mode=Debug $LAZ_OPT $PROJECT_LPI_UNIT_TEST_PATH

# Start the unit test
  - source ./scripts/travis_unit_test.sh

before_deploy:
# Build trackereditor project (Release mode)
  - lazbuild --build-mode=Release $LAZ_OPT $PROJECT_LPI_EDITOR_PATH

# Create the zip file for deployment
  - source ./scripts/travis_deploy.sh

deploy:
  provider: releases
  prerelease: $PROJECT_PRERELEASE
  skip_cleanup: true
  api_key:
    secure: $PROJECT_DEPLOY_PUBLIC_KEY
  file: "${RELEASE_ZIP_FILE}"
  on:
    tags: true 
    repo: $PROJECT_REPO

