# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

# Suppress the warning with the online Travis WebLint
language: generic

sudo: required
dist: trusty

env:
  global:
    - LPI_EDITOR_PATH=source/project/tracker_editor
    - LPI_UNIT_TEST_PATH=source/project/unit_test
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0

# For windows build (win32) use linux wine.
matrix:
  include:
    - os: linux
      env: LAZ_VER=1.6.2  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.6.2
    - os: osx
      env: LAZ_VER=1.6.2
      osx_image: xcode8.3


before_install:
# Start virtual display server
  - Xvfb $DISPLAY &

install:
# Install prerequisites (fpc/lazarus/wine/qemu)
  - ./travis-lazarus/.travis.install.py

# install openSSL on macOS
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl; fi
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo brew link openssl --force; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then openssl version; fi

script:
# Build trackereditor project
  - lazbuild $LAZ_OPT $LPI_EDITOR_PATH/trackereditor.lpi

# Build unit test project
  - lazbuild $LAZ_OPT $LPI_UNIT_TEST_PATH/tracker_editor_test.lpi

# Start the unit test
  - source ./scripts/travis_unit_test.sh

before_deploy:
  - source ./scripts/travis_deploy.sh

deploy:
  provider: releases
  prerelease: false
  skip_cleanup: true
  api_key:
    secure: "4SPoXhlWCKAf22vsrLUIm8CAMpwb+vXtb4VN4GL0F+DVEyb8JFMpc2o4Rd1bSP995c5EVm0FkOiBTHZNCU2nDY/xV6Mmp489fPVDXyFq4uZxveOXrIEbloRuMyyMZSpjKe3UaW3JRoPCsYDjv2o9ToqyBuE6YBbBoS/DicCmVUlJS6FfsC4m+RKwTTetIIfLXEFwyL0dyWDTf1c5hvnQEIwgzKRSJ8DjfwygqxgRJqrvOxi82bFIZDjoyXTSoMs2N38woTRdgrh6OwtI/W3PqrjKxI8s3B1JiUosHZjG3A5LbcDtdQZXp92uSsKSUdcyrVs4NoxrgXcQpKkER9SmBLLKp/y+839Dhe9HuKJKxZ3UTuDX2zBYHYfd5kxu9is0iQjUPRUFawwLTF4xmvQQFwHkI4mXY1BwOBsK7Ij+xhFK+0KT3BP9ZLLTgAQOCyNZftMyx+LXL0wrwkcySbfKK5g9MIOzXKJYuMS9wzsV5NJVN+iZOhnpmnUZ9q46SiEnWfoAsIiyhdwJp45hgfqVAoObWRlSOQiXvcqsnfJRD8c/NqI7D+/9GmSLcQs5Tpog9PxKA+KdQS0QuHElkVFPfo5kUiyItj8VCA0q/jz2urhRazxqL6kHMPiDi1aYgLq+ibRH081AygYmzQhIb7d97/ekdEfHSY/Tdtn3ozIL/2M="
  file: "${RELEASE_ZIP_FILE}"
  on:
    tags: true 
    repo: GerryFerdinandus/bittorrent-tracker-editor

