# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

sudo: true

os:
  - linux
  - osx

env:
  global:
    - LPIEDITORPATH=source/project/tracker_editor
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:	#For linux and mac osx build
    - LAZ_VER=1.4.4

matrix:		#For windows build with linux wine. Use the same lazarus version as linux/mac build.
  include:
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"

before_install:
    # Start virtual display server
  - sh -e /etc/init.d/xvfb start || true

install:
    # Install prerequisites (fpc/lazarus/wine/qemu)
  - ./travis-lazarus/.travis.install.py

script:
  - lazbuild $LAZ_OPT $LPIEDITORPATH/trackereditor.lpi      # Build trackereditor project
