name: bittorrent-tracker-editor
version: '1.33.0'
base: core22
summary: Add or remove tracker from torrent files.
description: |
  Features:
  - Select one torrent file or a folder with torrent files.
  - Add one or more trackers at the same time.
  - Remove one or more trackers at the same time.
  - Remove all the trackers to create trackerless torrent. DHT torrent
  - Change public/private flag. Warning: This will change the torrent info HASH.
  - Show torrent files content.
  - Download stable trackers from newTrackon or ngosang
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  bittorrent-tracker-editor:
    extensions:
      - kde-neon
    command: app/trackereditor
    environment:
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - home
      - network
      - removable-media
      - pulseaudio

parts:
  bittorrent-tracker-editor:
    source: https://github.com/GerryFerdinandus/bittorrent-tracker-editor.git
    plugin: nil
    override-build: |
      snapcraftctl build
      lazbuild --build-mode=Release --widgetset=qt5 source/project/tracker_editor/trackereditor.lpi
      mkdir $CRAFT_PART_INSTALL/app
      mv enduser/trackereditor $CRAFT_PART_INSTALL/app
    build-packages:
      - fpc
      - fpc-source
      - lcl-nogui
      - lazarus
      - libqt5pas-dev

  libQt5Pas:
    plugin: nil
    stage-packages:
      - libqt5pas1
    prime:
      - usr/lib/*/libQt5Pas.*

# Only 2 files are explicitly added in this snap: trackereditor + libQt5Pas.so
# No need to add a cleanup process. There's nothing to clean up.
#
# Use: 'unsquashfs *.snap' to look what is inside the snap file.
